
#pragma once

#define MSDFGEN_PUBLIC
#define MSDFGEN_EXT_PUBLIC

#define MSDFGEN_VERSION 1.12.0
#define MSDFGEN_VERSION_MAJOR 1
#define MSDFGEN_VERSION_MINOR 12
#define MSDFGEN_VERSION_REVISION 0
#define MSDFGEN_COPYRIGHT_YEAR 2024

#define MSDFGEN_USE_CPP11
#define MSDFGEN_EXTENSIONS
#define MSDFGEN_USE_TINYXML2
#define MSDFGEN_USE_LIBPNG
